/**
 * Changelog — generated from the real git history, oldest to newest.
 *
 * DO NOT hand-edit entries: regenerate after merges with the script the
 * header of scripts/generate-changelog note describes (git log --reverse
 * --format='%ad|%h|%s' --date=short parsed by conventional-commit type).
 * Milestones are the one curated layer: hash -> why that commit mattered.
 */

export type ChangeType = 'feat' | 'fix' | 'chore' | 'docs' | 'perf' | 'refactor' | 'redesign' | 'polish' | 'deploy' | 'test' | 'style' | 'other';

export interface ChangeEntry {
	date: string;
	hash: string;
	type: ChangeType;
	scope: string | null;
	title: string;
	/** Set on the ~14 commits that defined an era — rendered as timeline epochs. */
	milestone?: string;
}

export const CHANGELOG: ChangeEntry[] = [
	{ date: '2026-05-15', hash: '04c8672', type: 'feat', scope: null, title: "initialize project with responsive structure, custom design system, and hero animation styling", milestone: "Repo initiation \u2014 static onboarding site with the first design system." },
	{ date: '2026-05-15', hash: 'aece5dc', type: 'feat', scope: null, title: "add client onboarding landing page with service overview and service level expectations" },
	{ date: '2026-05-16', hash: '8c71125', type: 'feat', scope: null, title: "v3 onboarding kill chain - pricing, PM dashboard, agreement details, aligned design system" },
	{ date: '2026-05-16', hash: '1f6760d', type: 'feat', scope: null, title: "add roadmap section - phase timeline + post-launch scaling milestones" },
	{ date: '2026-05-16', hash: '5e2bc7d', type: 'feat', scope: null, title: "design system unification - tokens.css + portal.css + shared nav + cross-page links" },
	{ date: '2026-05-16', hash: '0ddf92d', type: 'redesign', scope: null, title: "index.html matches onboarding design DNA - purge cyberpunk styles, unified dark ambient system" },
	{ date: '2026-05-16', hash: '1bd824f', type: 'fix', scope: null, title: "robust responsiveness - hamburger nav, mobile drawer, all grid breakpoints for both pages" },
	{ date: '2026-05-16', hash: 'ec18179', type: 'feat', scope: null, title: "deploy script + gitignore - one-command commit/push/deploy pipeline" },
	{ date: '2026-05-16', hash: '3390652', type: 'feat', scope: null, title: "hide portal-only navigation links while the PIN gate is locked" },
	{ date: '2026-05-16', hash: '39d54c3', type: 'refactor', scope: null, title: "update influencer UI components and standardize spark chart rendering" },
	{ date: '2026-05-16', hash: 'b0d909a', type: 'feat', scope: null, title: "update pricing display with discounted rate, strikethrough, and limited time offer badge" },
	{ date: '2026-05-16', hash: '0d74e32', type: 'feat', scope: null, title: "enhance spark chart with area gradients and updated styling for dashboard components" },
	{ date: '2026-05-17', hash: '8e5c92f', type: 'feat', scope: null, title: "decouple data from core script using JSON files and a new async data-loader utility" },
	{ date: '2026-05-17', hash: '785c618', type: 'feat', scope: null, title: "implement automated build script for client-specific site generation and update onboarding template to use WhatsApp instead of Telegram" },
	{ date: '2026-05-17', hash: '59141a4', type: 'feat', scope: null, title: "add automated MSA PDF generation and DocuSeal template integration script" },
	{ date: '2026-05-20', hash: '5f797f6', type: 'feat', scope: "honeyforx", title: "remove Nova references, align aggregator-based SOW and secure BYOK keys, and integrate high-fidelity UGC personas" },
	{ date: '2026-05-20', hash: '08f3abc', type: 'feat', scope: null, title: "add AI influencer data roster and architecture documentation to project backup" },
	{ date: '2026-05-20', hash: 'e9e143c', type: 'feat', scope: null, title: "consolidate onboarding portal, integrate Postiz connections, and enforce FDA/FTC warnings", milestone: "The client portal era begins: onboarding portal and first social-connection plumbing." },
	{ date: '2026-05-20', hash: '3e2ddea', type: 'style', scope: null, title: "remove fda/ftc compliance warnings and ai-generated watermark badges from generated scripts" },
	{ date: '2026-05-20', hash: 'c03e81d', type: 'style', scope: null, title: "resolve button.pg-nav-link active tab override issue" },
	{ date: '2026-05-20', hash: '7d1bd74', type: 'chore', scope: "honeyforx", title: "update pricing links to collect payments through Monarch Stack Stripe" },
	{ date: '2026-05-20', hash: '80bb9d4', type: 'feat', scope: null, title: "implement operations portal view switching, drag-and-drop content calendar scheduler, correct stripe links, and deploy build" },
	{ date: '2026-05-20', hash: 'b028fad', type: 'feat', scope: null, title: "consolidate operations dashboard layout and subview routing" },
	{ date: '2026-05-20', hash: '66f5050', type: 'fix', scope: null, title: "resolve landing page initialization crash, navigation active scroll state, and missing exit portal controls" },
	{ date: '2026-05-20', hash: 'ed29062', type: 'fix', scope: null, title: "resolve selector typo body.portal-active hiding navbar in styles.css" },
	{ date: '2026-05-21', hash: '36ea8be', type: 'fix', scope: null, title: "resolve page scrolling and black view state on hash routing in portal mode" },
	{ date: '2026-05-21', hash: '1c392b5', type: 'feat', scope: null, title: "add client MSA PDF download button to onboarding agreement view" },
	{ date: '2026-05-21', hash: 'ae30be5', type: 'other', scope: null, title: "legal: remove photos, justify text alignment, and avoid orphan headings in MSA" },
	{ date: '2026-05-21', hash: 'e7fb1e2', type: 'chore', scope: null, title: "update deploy.ps1 to target compiled dist/honeyforx folder" },
	{ date: '2026-05-21', hash: '35967d8', type: 'other', scope: null, title: "pin 2026 and multi-page portal paths" },
	{ date: '2026-05-21', hash: 'a9f4d14', type: 'chore', scope: null, title: "fix deploy.ps1 error handling and warning output" },
	{ date: '2026-05-21', hash: '53126b8', type: 'other', scope: null, title: "fix PIN.init syntax error in script.js" },
	{ date: '2026-05-21', hash: 'ddabebf', type: 'other', scope: null, title: "fix page template nesting in build.js" },
	{ date: '2026-05-24', hash: '42b9dc8', type: 'chore', scope: null, title: "gitignore cleanup \u2014 untrack backup/, env_vars.txt, db_dump.txt, add temp_test/ and IDE patterns" },
	{ date: '2026-05-24', hash: 'de19922', type: 'feat', scope: null, title: "PM dashboard kanban board, search/filter system, onboarding docs" },
	{ date: '2026-05-29', hash: '4612c60', type: 'style', scope: "pdf", title: "fix whitespace, layout, and emoji rendering issues on Windows" },
	{ date: '2026-05-29', hash: 'aeaeffc', type: 'style', scope: "pdf", title: "update effective date to 05/29/2026 in configuration and tracker" },
	{ date: '2026-05-29', hash: 'd3285aa', type: 'feat', scope: "pdf", title: "add unified onboarding packet generation, update effective date to 05/29/2026, and align MSA & portal styling" },
	{ date: '2026-05-30', hash: 'a20276e', type: 'feat', scope: null, title: "add dashboard modules (composer, trends, calendar, inbox, persona-config, api) + Composio/Apify integration" },
	{ date: '2026-05-30', hash: '2a89cb4', type: 'fix', scope: null, title: "PIN 2025->2026, replace dashboard.html redirects with SPA view switching" },
	{ date: '2026-05-30', hash: '8f92abe', type: 'fix', scope: null, title: "portal blank screen - hide topbar/footer, explicitly call switchPortalView(dashboard)" },
	{ date: '2026-05-30', hash: 'a0861ac', type: 'fix', scope: null, title: "revert to dashboard.html redirect (PIN=2026), build system handles sub-pages" },
	{ date: '2026-05-30', hash: '3001d73', type: 'other', scope: null, title: "trigger: redeploy with build config" },
	{ date: '2026-05-30', hash: '6282c75', type: 'fix', scope: null, title: "add wrangler.toml to set pages_build_output_dir=dist/honeyforx" },
	{ date: '2026-05-30', hash: 'c606646', type: 'fix', scope: null, title: "remove wrangler.toml - was causing Workers deploy instead of Pages static" },
	{ date: '2026-05-30', hash: '53fec15', type: 'feat', scope: null, title: "mobile-first UX overhaul - responsive sidebar/panel, profile dropdown, dead element removal, nav consolidation" },
	{ date: '2026-05-30', hash: '119ba51', type: 'feat', scope: null, title: "brand brief interview module with Firecrawl integration, 8-step form, viability assessment", milestone: "Brand Brief is born \u2014 the Firecrawl-powered brand interview wizard." },
	{ date: '2026-05-30', hash: 'cf35f83', type: 'feat', scope: null, title: "n8n brand brief workflows (crawl + assessment), direct webhook endpoints, Telegram notifications" },
	{ date: '2026-05-30', hash: '4cc1f1e', type: 'polish', scope: null, title: "SVG icons replace all emoji, header/sidebar/dropdown UX upgrade, focus rings, animations" },
	{ date: '2026-05-30', hash: 'ad1ab2c', type: 'fix', scope: null, title: "brand-brief missing from build pipeline, header cutoff, workspace height" },
	{ date: '2026-05-30', hash: '38eec70', type: 'fix', scope: null, title: "auto-init all modules on built pages, profile cutoff, dropdown links, layout overflow" },
	{ date: '2026-05-30', hash: '9ebcdfd', type: 'fix', scope: null, title: "init guards for all modules, robust crawl error handling, Firecrawl v2 upgrade" },
	{ date: '2026-05-30', hash: '7d1678b', type: 'feat', scope: null, title: "brand brief crawl results now show logo, title, description, hex values; auto-fills identity fields" },
	{ date: '2026-05-30', hash: 'e25fa19', type: 'feat', scope: null, title: "comprehensive mobile responsiveness - landing page, dashboard, brand brief wizard, all breakpoints" },
	{ date: '2026-05-30', hash: '2d2a150', type: 'feat', scope: null, title: "full Firecrawl branding display - logo, favicon, OG image, fonts, typography, spacing, buttons, personality, confidence, markdown + mobile overflow fixes + inline grid cleanup" },
	{ date: '2026-05-30', hash: '3a63fc4', type: 'fix', scope: null, title: "Dockerfile COPY paths relative to repo root for Easypanel build context" },
	{ date: '2026-05-30', hash: '7c6b14e', type: 'fix', scope: null, title: "use npm install --omit=dev (no lockfile available for npm ci)" },
	{ date: '2026-05-30', hash: '0d9f1ae', type: 'fix', scope: null, title: "chown /data to node user (SQLITE_CANTOPEN permission fix)" },
	{ date: '2026-05-30', hash: '5194176', type: 'fix', scope: null, title: "remove USER node \u2014 Easypanel volumes mount as root" },
	{ date: '2026-05-30', hash: '0041524', type: 'fix', scope: null, title: "replace ss/netstat with TCP socket probe in mail health check" },
	{ date: '2026-05-30', hash: '11a9915', type: 'other', scope: null, title: "debug: add filesystem diagnostics for SQLITE_CANTOPEN" },
	{ date: '2026-05-31', hash: '2fa6692', type: 'chore', scope: null, title: "remove debug diagnostics (SQLITE_CANTOPEN confirmed fixed)" },
	{ date: '2026-05-31', hash: 'daeb2da', type: 'feat', scope: null, title: "add AgenticMail inbox API (POST /api/inboxes, GET /api/inboxes/:id/messages)" },
	{ date: '2026-05-31', hash: 'd579d38', type: 'feat', scope: null, title: "local inbox fallback when mail API unreachable" },
	{ date: '2026-05-31', hash: '6b35b2e', type: 'fix', scope: null, title: "use dynamic import for ESM-only cloakbrowser" },
	{ date: '2026-05-31', hash: '849182d', type: 'fix', scope: null, title: "trust proxy + ESM cloakbrowser import" },
	{ date: '2026-05-31', hash: '4ec1a3f', type: 'fix', scope: null, title: "add playwright-core peer dep for cloakbrowser" },
	{ date: '2026-05-31', hash: 'ceb9866', type: 'fix', scope: null, title: "use MAIL_DOMAIN for inbox emails, add GV env fallback for phone verify" },
	{ date: '2026-05-31', hash: '9c386ef', type: 'feat', scope: null, title: "install Stalwart binary, add pipe delivery to inbox JSON, expose SMTP port 25" },
	{ date: '2026-05-31', hash: 'd3a78ec', type: 'fix', scope: null, title: "correct Stalwart binary URL to v0.16.7" },
	{ date: '2026-05-31', hash: 'de11881', type: 'fix', scope: null, title: "Stalwart v0.16 config format + deferred startup" },
	{ date: '2026-05-31', hash: 'e59c6fa', type: 'fix', scope: null, title: "stalwart autostart=true, remove premature supervisorctl call" },
	{ date: '2026-05-31', hash: '4b03cc2', type: 'fix', scope: null, title: "write Stalwart config to /tmp to avoid stale volume race condition" },
	{ date: '2026-05-31', hash: '7aa88b1', type: 'fix', scope: null, title: "replace broken OAuth popup (GET to POST-only webhook) with working manual handle connect flow" },
	{ date: '2026-05-31', hash: '8531193', type: 'fix', scope: null, title: "write Stalwart config via bash heredoc, eliminate Node.js script dependency" },
	{ date: '2026-05-31', hash: '048f8dc', type: 'fix', scope: null, title: "strip CRLF from entrypoint.sh in Docker build, add .gitattributes for shell scripts" },
	{ date: '2026-05-31', hash: 'eedaf6d', type: 'fix', scope: null, title: "downgrade to Stalwart v0.15.6 (TOML config), v0.16 dropped TOML entirely" },
	{ date: '2026-05-31', hash: '83079cc', type: 'feat', scope: null, title: "sidebar 10-to-5, mega-view tabs, collapsible panels, click-outside-close" },
	{ date: '2026-05-31', hash: '7eb1d23', type: 'fix', scope: null, title: "use Stalwart v0.15.4 correct release URL" },
	{ date: '2026-05-31', hash: 'ff0bf5c', type: 'fix', scope: null, title: "extract Stalwart binary directly to /usr/local/bin, rename stalwart->stalwart-mail" },
	{ date: '2026-05-31', hash: '73218bd', type: 'fix', scope: null, title: "use official stalwartlabs/stalwart:v0.15.4 image as base" },
	{ date: '2026-05-31', hash: 'ba2df88', type: 'fix', scope: null, title: "v0.15 storage config - named rocksdb store with internal directory" },
	{ date: '2026-05-31', hash: '658d110', type: 'fix', scope: null, title: "storage.directory inline reference for v0.15" },
	{ date: '2026-05-31', hash: 'bf54e04', type: 'feat', scope: null, title: "add Stalwart pipe delivery to inbox-deliver.js + catch-all Sieve script" },
	{ date: '2026-05-31', hash: '0dba462', type: 'fix', scope: null, title: "click-outside-close, remove duplicate handler, wire analytics KPIs, profile dropdown fix" },
	{ date: '2026-05-31', hash: 'ff19b93', type: 'fix', scope: null, title: "enable Stalwart relay+catch-all to accept any RCPT without accounts" },
	{ date: '2026-05-31', hash: 'd6aef8d', type: 'fix', scope: null, title: "remove storage.directory to bypass RCPT verification, relay=true" },
	{ date: '2026-05-31', hash: '7326f65', type: 'fix', scope: null, title: "build system - handle switchMegaView buttons and profile dropdown links for sub-pages" },
	{ date: '2026-05-31', hash: '29c280d', type: 'refactor', scope: null, title: "replace Stalwart with Node.js smtp-server - simpler, no binary config issues" },
	{ date: '2026-05-31', hash: '3c95f71', type: 'fix', scope: null, title: "SMTP on port 2525 (no root needed), map 25->2525 in Easypanel" },
	{ date: '2026-05-31', hash: '434d390', type: 'fix', scope: null, title: "desktop sidebar/analytics collapse buttons visible, mega tab bars on sub-pages, brand brief accessible" },
	{ date: '2026-05-31', hash: 'cf6d019', type: 'fix', scope: null, title: "force redeploy smtp-server port 25" },
	{ date: '2026-05-31', hash: '5be7364', type: 'refactor', scope: null, title: "single source of truth - agents.json with soul/tools/skills/heartbeat, remove DASH_AGENTS/mockAgents duplicates, data bridge populates INFLUENCERS from DATA.agents" },
	{ date: '2026-05-31', hash: '5863776', type: 'fix', scope: null, title: "use PersonaGenConfig for webhook URLs in channel-decoder.js and content-forge.js instead of hardcoded URLs" },
	{ date: '2026-05-31', hash: '12f3eaf', type: 'refactor', scope: "Phase3", title: "real Account Factory - replace simulateFactoryPipeline with pollFactoryStatus, dynamic sidebar from DATA.agents, replace alert/confirm with toasts, add New Avatar button" },
	{ date: '2026-05-31', hash: '1f6079e', type: 'fix', scope: null, title: "restore Stalwart base image + directory catch-all + clear RocksDB on start (clears IP ban)" },
	{ date: '2026-05-31', hash: 'f08a755', type: 'refactor', scope: "Phase4+5", title: "scrub all confirm/prompt/alert dialogs platform-wide, replace with toast+auto-save UX, remove all setTimeout fakes from SocialConnections" },
	{ date: '2026-05-31', hash: 'c7f8318', type: 'feat', scope: null, title: "Avatar Wizard (5-stage), Grok Imagine photo generation via n8n, Content Forge frequency selector (1d/7d/1m/1y)" },
	{ date: '2026-05-31', hash: 'fb7a71a', type: 'fix', scope: null, title: "wire right panel KPIs to DASH_AGENTS, show collapse buttons on desktop, add mega tab bars" },
	{ date: '2026-05-31', hash: '4d3ef9b', type: 'fix', scope: null, title: "remove hardcoded KPI 13, all stats now dynamic from DASH_AGENTS" },
	{ date: '2026-05-31', hash: 'eadd751', type: 'fix', scope: null, title: "remove scroll trap - content flows natively, responsive grid transitions, remove orphaned CSS" },
	{ date: '2026-05-31', hash: '3ea3fb1', type: 'fix', scope: null, title: "wire KPI row from DASH_AGENTS data, replace hardcoded 13, fix CSS overflow" },
	{ date: '2026-05-31', hash: '1f0e0af', type: 'polish', scope: null, title: "full UI/UX audit - WCAG contrast, focus-visible, disabled states, a11y, remove 91 duplicate CSS lines, semantic HTML" },
	{ date: '2026-05-31', hash: '2bb5377', type: 'polish', scope: null, title: "complete remaining audit items - data-testid, aria-busy, label-to-button chips, for attrs, token padding, bg alignment, dvh, CSS hover migration, main landmark" },
	{ date: '2026-05-31', hash: 'e59d3dc', type: 'fix', scope: "audit", title: "dynamic sparkline legend, real session health, generic AC placeholders, toast mobile, font-size floor, mega-tab-bar overflow" },
	{ date: '2026-05-31', hash: '04e8e3f', type: 'feat', scope: null, title: "MVP flow fixes - section isolation on mega-tabs, calendar init, legacy data conversion, clickable agent rows, quick-action buttons, published post links" },
	{ date: '2026-05-31', hash: '9d0c704', type: 'feat', scope: null, title: "Bulk Schedule Generator wizard + Coming Soon on Email/SMS inbox" },
	{ date: '2026-05-31', hash: 'de105ba', type: 'fix', scope: "nav", title: "hamburger inside header bar, fix all view scroll-to-top, scrollIntoView for mega-tab sections" },
	{ date: '2026-05-31', hash: 'f6d3d82', type: 'fix', scope: "build", title: "regex patterns broken by data-testid attrs - sidebar/mega-tab buttons not converting to links in sub-pages" },
	{ date: '2026-06-01', hash: '4243286', type: 'fix', scope: null, title: "scroll blocked by body overflow:hidden, add Avatar Wizard button to generator + dashboard quick actions" },
	{ date: '2026-06-01', hash: '0069030', type: 'fix', scope: null, title: "contained scroll within dash-center-panel, proper mega-tab styling, toolbar button wrap, mobile calendar 1-col" },
	{ date: '2026-06-01', hash: '7203cfd', type: 'fix', scope: "critical", title: "auto-init all modules on DOMContentLoaded for compiled sub-pages \u2014 fixes blank Trends/Decoder/Forge/Agents/Inbox/BrandBrief pages" },
	{ date: '2026-06-01', hash: '3991c8d', type: 'refactor', scope: null, title: "avatar wizard inline like brand-brief pattern" },
	{ date: '2026-06-01', hash: '898b98a', type: 'other', scope: null, title: "merge user edits: simplified nav, removed landing page, pin-gate default visible + wizard mount" },
	{ date: '2026-06-01', hash: '21fd348', type: 'other', scope: null, title: "remove landing page, PIN-gate as entry point" },
	{ date: '2026-06-04', hash: 'c1acdda', type: 'feat', scope: null, title: "add OG share image + meta tags for honeyx.monarchstack.com" },
	{ date: '2026-06-04', hash: '359a3a6', type: 'fix', scope: null, title: "update PIN screen branding to HoneyX + MonarchStack" },
	{ date: '2026-06-05', hash: '5a1c5b5', type: 'other', scope: null, title: "E2E Puppeteer verification of Intelligence Wizard complete and passed" },
	{ date: '2026-06-05', hash: 'e3cf929', type: 'deploy', scope: null, title: "align live target domain to personagen-demo and update playbook" },
	{ date: '2026-06-05', hash: '1454357', type: 'docs', scope: null, title: "add detailed CAUTION on deployment assumptions to avoid future mistakes" },
	{ date: '2026-06-08', hash: '3294f22', type: 'other', scope: null, title: "Fix database connection and accounts API uuid casting errors" },
	{ date: '2026-06-08', hash: '026c467', type: 'other', scope: null, title: "Implement true OAuth redirect flow for social accounts" },
	{ date: '2026-06-08', hash: 'e472a54', type: 'other', scope: null, title: "Implement native RSS Feed auto-repurposing and automatic posting" },
	{ date: '2026-06-08', hash: 'abcb1df', type: 'refactor', scope: null, title: "merge Connected Accounts into Persona Config page" },
	{ date: '2026-06-08', hash: '14b229e', type: 'other', scope: null, title: "docs/config: scrub pages.dev domain and set custom domain" },
	{ date: '2026-06-08', hash: '33dd420', type: 'other', scope: null, title: "ui: implement lean operations layout" },
	{ date: '2026-06-09', hash: '9fe5de3', type: 'fix', scope: null, title: "consolidate codebase, add social tags, and upgrade docker to node 22" },
	{ date: '2026-06-09', hash: '38ac9b4', type: 'fix', scope: null, title: "remove wrangler build-time check to support Docker compile" },
	{ date: '2026-06-09', hash: 'e10c238', type: 'fix', scope: null, title: "restore full dashboard sidebar navigation and resolve svelte-check types" },
	{ date: '2026-06-09', hash: '8adf8c1', type: 'other', scope: null, title: "production: completed analytics closed-loop, integrated honeyforx.com, and purged cloudflare pages remnants" },
	{ date: '2026-06-09', hash: '490bb7b', type: 'deploy', scope: null, title: "transition accounts connect to true oauth and update brand products" },
	{ date: '2026-06-09', hash: '13b2126', type: 'deploy', scope: null, title: "enhance fetch error handler to surface helpful API setup messages" },
	{ date: '2026-06-09', hash: 'ac68c0a', type: 'deploy', scope: null, title: "update & verify 2026-06-09 22:15" },
	{ date: '2026-06-09', hash: '05a26f3', type: 'fix', scope: null, title: "resolve Composio OAuth connection link payload requiring auth_config_id and update key" },
	{ date: '2026-06-09', hash: '5ec65bd', type: 'fix', scope: null, title: "support both snake_case redirect_url and camelCase redirectUrl from Composio response" },
	{ date: '2026-06-09', hash: '5449d38', type: 'other', scope: null, title: "'deploy:" },
	{ date: '2026-06-09', hash: '46c9dcc', type: 'deploy', scope: null, title: "update & verify 2026-06-09 22:50" },
	{ date: '2026-06-09', hash: 'b2da1b4', type: 'feat', scope: null, title: "implement portal layout, dashboard, persona configuration, and agent chat infrastructure" },
	{ date: '2026-06-09', hash: '7c6b291', type: 'feat', scope: null, title: "implement agent configuration page with identity, autonomy, and platform management tabs" },
	{ date: '2026-06-09', hash: 'ebd82b9', type: 'fix', scope: "overseer", title: "resolve safeGetSession, missing summary column, and Svelte 5 const placement" },
	{ date: '2026-06-09', hash: 'b7e0986', type: 'style', scope: null, title: "refine borders, backgrounds, and user badge in layout" },
	{ date: '2026-06-10', hash: 'd8e13ab', type: 'feat', scope: null, title: "integrate Composio for agent social media account management and automated posting functionality" },
	{ date: '2026-06-10', hash: 'cdb4551', type: 'feat', scope: null, title: "restore standalone chat route, implement inbox server loader and layout syncing" },
	{ date: '2026-06-10', hash: '39e0b63', type: 'other', scope: null, title: "config: map Google OAuth environment variables in docker-compose.yml for supabase-auth" },
	{ date: '2026-06-10', hash: '4b73ad0', type: 'style', scope: null, title: "establish global Vanilla-shadcn design system and refactor auth and agent chat components" },
	{ date: '2026-06-10', hash: '7593bee', type: 'deploy', scope: null, title: "update & verify 2026-06-10 13:12" },
	{ date: '2026-06-10', hash: '337051a', type: 'feat', scope: null, title: "implement favorite handle, collapsible cards, and reveal/hide platform controls in connected accounts" },
	{ date: '2026-06-10', hash: '4a7f22c', type: 'chore', scope: null, title: "consolidate services into docker-compose and fix dockerfile paths for isolated build contexts" },
	{ date: '2026-06-10', hash: 'c410d9c', type: 'fix', scope: null, title: "use npm install instead of npm ci in mcp-bridge as there is no package-lock.json" },
	{ date: '2026-06-10', hash: '7ccca91', type: 'feat', scope: null, title: "implement agent chat interface with persistent session history and toast notifications" },
	{ date: '2026-06-10', hash: '2f227a9', type: 'fix', scope: null, title: "harden Composio social connection flow" },
	{ date: '2026-06-10', hash: '50df718', type: 'feat', scope: null, title: "stabilize runtime contracts and align service boundaries" },
	{ date: '2026-06-11', hash: '639d563', type: 'feat', scope: null, title: "implement calendar and inbox routing pages with content scheduling and demo data support" },
	{ date: '2026-06-11', hash: 'e6607eb', type: 'feat', scope: null, title: "implement interactive AgentChat component and integrate into portal inbox page" },
	{ date: '2026-06-12', hash: 'a216239', type: 'feat', scope: null, title: "add new log file for agent testing process" },
	{ date: '2026-06-15', hash: 'd31c2e2', type: 'feat', scope: null, title: "implement full-stack persona agent platform with SvelteKit, Supabase, Stripe billing, and Composio integration", milestone: "The platform rewrite: full-stack SvelteKit + Supabase persona platform." },
	{ date: '2026-06-15', hash: 'c2dde25', type: 'feat', scope: null, title: "implement MCP server bridge with Supabase tools for connection monitoring and agent chat management" },
	{ date: '2026-06-15', hash: '5484b84', type: 'feat', scope: null, title: "implement Hermes service to manage, seed, and link overseer agent configurations" },
	{ date: '2026-06-15', hash: 'b200859', type: 'feat', scope: null, title: "add scratch scripts for querying Supabase tables and searching local transcript logs" },
	{ date: '2026-06-15', hash: '4074a0c', type: 'feat', scope: null, title: "create search-captix-all.js script to automate customer data retrieval and analysis" },
	{ date: '2026-06-15', hash: '8cd0928', type: 'refactor', scope: null, title: "remove unused and deprecated codebase files" },
	{ date: '2026-06-15', hash: '00f2cb3', type: 'other', scope: null, title: "security: remediate critical and high-risk security vulnerabilities" },
	{ date: '2026-06-15', hash: 'f6480dd', type: 'chore', scope: null, title: "run prettier formatting and remove trailing whitespace" },
	{ date: '2026-06-15', hash: '5765890', type: 'chore', scope: null, title: "scrub internal L2G infrastructure dependencies and enforce environment variables" },
	{ date: '2026-06-15', hash: '3b626b6', type: 'docs', scope: null, title: "add root README.md with architecture overview and project roadmap" },
	{ date: '2026-06-15', hash: 'b5badf7', type: 'docs', scope: null, title: "update mermaid diagram syntax for better node labeling and connection clarity in README" },
	{ date: '2026-06-15', hash: '4f183a4', type: 'docs', scope: null, title: "fix space in subgraph ID in README mermaid diagram to resolve parse error" },
	{ date: '2026-06-15', hash: 'd559ac8', type: 'chore', scope: null, title: "remove scratch files and internal test scripts for client handover" },
	{ date: '2026-06-15', hash: 'abcc57f', type: 'chore', scope: null, title: "delete obsolete tools directory and legacy development scripts" },
	{ date: '2026-06-15', hash: '60c3d70', type: 'feat', scope: null, title: "add agent chat interface and inbox page for messaging functionality" },
	{ date: '2026-06-15', hash: '6a952b8', type: 'feat', scope: null, title: "implement agent dashboard with interactive roster, status management, and persona configuration routing" },
	{ date: '2026-06-15', hash: '29c13f8', type: 'feat', scope: null, title: "implement content calendar route with post scheduling functionality and Composio integration" },
	{ date: '2026-06-15', hash: '7f9228a', type: 'feat', scope: null, title: "add calendar scheduling, content forging, and brand brief management routes and UI." },
	{ date: '2026-06-15', hash: '6bc7989', type: 'feat', scope: null, title: "add scout intelligence page with trend monitoring and agent-based content generation" },
	{ date: '2026-06-15', hash: '48201b3', type: 'feat', scope: null, title: "add portal layout and initial calendar, scout, and trends routes" },
	{ date: '2026-06-15', hash: '49008e8', type: 'feat', scope: null, title: "add calendar route with post scheduling and content forge integration" },
	{ date: '2026-06-15', hash: 'ffc9ddb', type: 'feat', scope: null, title: "implement calendar view and content forge integration for post scheduling" },
	{ date: '2026-06-15', hash: '7402884', type: 'feat', scope: null, title: "implement multi-step agent creation wizard and placeholder pages for portal modules" },
	{ date: '2026-06-16', hash: '2ec8bbb', type: 'feat', scope: null, title: "complete standalone Content Forge (Blueprint Manager) rebuild and fix calendar reactivity navigation loop" },
	{ date: '2026-06-16', hash: '9a324b9', type: 'feat', scope: null, title: "scaffold portal routing and server hooks while archiving documentation" },
	{ date: '2026-06-16', hash: 'd3d750f', type: 'feat', scope: null, title: "add auth layout and pages and initialize project graph metadata" },
	{ date: '2026-06-16', hash: '8657af6', type: 'feat', scope: null, title: "add interactive D3.js visualization for project directory structure" },
	{ date: '2026-06-16', hash: 'd30eb2c', type: 'feat', scope: null, title: "add agent workflows, verification rules, and engine integration tests" },
	{ date: '2026-06-16', hash: '801f188', type: 'feat', scope: null, title: "implement sign-up and login pages with global CSS configuration" },
	{ date: '2026-06-16', hash: '1442260', type: 'feat', scope: null, title: "add agent chat interface for conversational interaction with personas and overseer modules" },
	{ date: '2026-06-16', hash: '9de0286', type: 'feat', scope: null, title: "implement agent chat server with tool execution and initial Composio social integration framework" },
	{ date: '2026-06-16', hash: '075ac4d', type: 'feat', scope: null, title: "implement agent configuration dashboard for managing identity, social metrics, and platform settings" },
	{ date: '2026-06-16', hash: 'dcba3c0', type: 'other', scope: null, title: "auth: remove Google sign-in and keep optional admin PIN" },
	{ date: '2026-06-17', hash: 'd2461e6', type: 'feat', scope: null, title: "initialize portal routing, database services, and dashboard analytics engine" },
	{ date: '2026-06-17', hash: '161439d', type: 'feat', scope: null, title: "implement Composio social media integration client and add platform sync API route" },
	{ date: '2026-06-18', hash: '43e0012', type: 'feat', scope: null, title: "implement core agentic workflow including content generation, trend analysis, and competitor auditing tools" },
	{ date: '2026-06-18', hash: '4fe719c', type: 'feat', scope: null, title: "implement agent chat architecture, including tool-enabled chat endpoints, session management, and dashboard integration." },
	{ date: '2026-06-22', hash: '0df9562', type: 'other', scope: null, title: "init feedback changes" },
	{ date: '2026-06-23', hash: 'f3abe7f', type: 'feat', scope: null, title: "implement calendar dashboard for post scheduling and content generation via forge" },
	{ date: '2026-06-24', hash: '505abe7', type: 'feat', scope: null, title: "implement posting MVP manual generation flow, live links, Firecrawl scraper, and agentic brand tools" },
	{ date: '2026-06-24', hash: 'c575ead', type: 'feat', scope: null, title: "implement user API key management system with Composio integration and database migrations" },
	{ date: '2026-06-26', hash: 'b1a4bd0', type: 'feat', scope: null, title: "implement project management dashboard and agent communication infrastructure" },
	{ date: '2026-06-27', hash: '1464158', type: 'feat', scope: null, title: "add antigravity rules, caveman/ponytail skill definitions, and new engine API server endpoint" },
	{ date: '2026-06-27', hash: 'ed09bd7', type: 'refactor', scope: null, title: "strip to orchestration & distribution only" },
	{ date: '2026-06-27', hash: '2e3fac3', type: 'fix', scope: null, title: "resolve boot race conditions and Instagram media URL query parameters" },
	{ date: '2026-06-29', hash: 'e047310', type: 'feat', scope: null, title: "implement autonomous agent content scheduling and management system" },
	{ date: '2026-06-29', hash: '40a79e5', type: 'feat', scope: null, title: "implement social publishing architecture with Zernio and Composio support, add brand brief management, and refactor persona routing logic.", milestone: "Social publishing architecture lands (Zernio) \u2014 personas can reach real accounts." },
	{ date: '2026-06-29', hash: '8aa0403', type: 'feat', scope: null, title: "implement persona content engine, blueprint management, and social media scheduling integration" },
	{ date: '2026-06-29', hash: '364a7ed', type: 'feat', scope: null, title: "add account management server route to sync Zernio and Composio social connections" },
	{ date: '2026-06-29', hash: '42c23a4', type: 'feat', scope: null, title: "implement UGC video generation pipeline with FFmpeg caption burning and schema-based per-agent configuration." },
	{ date: '2026-06-29', hash: '6f5f60e', type: 'feat', scope: null, title: "implement dashboard analytics, portal layouts, settings page, and API services for agents and infrastructure" },
	{ date: '2026-06-30', hash: '421aedc', type: 'fix', scope: null, title: "surface real posting errors, add delete flow, and fix cross-persona state bugs" },
	{ date: '2026-07-01', hash: 'a701c18', type: 'feat', scope: null, title: "add persona management dashboard with agent configuration, connection status, and content generation tools" },
	{ date: '2026-07-01', hash: '5bb3bb6', type: 'feat', scope: null, title: "implement agent management system with CRUD routes, persona dashboard, and automated content generation workflows" },
	{ date: '2026-07-01', hash: 'c1b1f37', type: 'feat', scope: null, title: "implement UGC content generation engine and UI modules for agent-based social media management" },
	{ date: '2026-07-01', hash: '11d7013', type: 'feat', scope: null, title: "implement post scheduling, platform publishing, and analytics sync module" },
	{ date: '2026-07-01', hash: '80f31ff', type: 'feat', scope: null, title: "implement social media scheduling and management infrastructure with platform integrations and UI post drawer" },
	{ date: '2026-07-01', hash: 'e0b4d50', type: 'feat', scope: null, title: "implement content calendar page with scheduling and content forge integration" },
	{ date: '2026-07-01', hash: '4c97068', type: 'feat', scope: null, title: "implement content generation engine, persona management, and calendar UI with SSRF-protected API endpoints" },
	{ date: '2026-07-02', hash: 'f8dac4c', type: 'feat', scope: null, title: "implement multi-stage generative AI pipeline for automated UGC and cinematic content creation" },
	{ date: '2026-07-02', hash: '1308850', type: 'feat', scope: null, title: "add shared content generation pipeline for UGC and cinematic video workflows" },
	{ date: '2026-07-04', hash: '6a3919a', type: 'feat', scope: null, title: "review queue + QC gate, Blotato provider, hook library, runway autopilot, persona UX", milestone: "Review Queue + QC gate + autopilot foundations \u2014 the approval workflow exists." },
	{ date: '2026-07-04', hash: 'a860215', type: 'feat', scope: null, title: "media provider failover \u2014 OpenRouter video API (Kling v3.0) as fal fallback" },
	{ date: '2026-07-04', hash: 'f171698', type: 'fix', scope: null, title: "scrape URL normalization + cost ledger, pricing matrix, calendar overhaul, favicon" },
	{ date: '2026-07-05', hash: '1a5bd0a', type: 'feat', scope: null, title: "Firecrawl branding-format brand guide, competitors, product-by-URL, feed tile grid, banner removal" },
	{ date: '2026-07-05', hash: 'a457b49', type: 'fix', scope: null, title: "coerce Firecrawl branding fonts (objects {family,role}) to name strings" },
	{ date: '2026-07-05', hash: '5076e37', type: 'feat', scope: null, title: "OpenRouter Nano-Banana composite failover, skills/tools editors, confirm parity, soul enrich" },
	{ date: '2026-07-05', hash: 'b3ab790', type: 'feat', scope: null, title: "implement account synchronization for Zernio and Blotato and add persona dashboard UI" },
	{ date: '2026-07-05', hash: 'cb67171', type: 'feat', scope: null, title: "generation composer + editable captions + platform registry consolidation" },
	{ date: '2026-07-05', hash: '9705c7f', type: 'feat', scope: null, title: "in-app Zernio OAuth connect flow \u2014 no more dead-end platform connects" },
	{ date: '2026-07-08', hash: '05bd4dd', type: 'feat', scope: null, title: "implement agent configuration management, content generation pipeline, and database support for brand briefs." },
	{ date: '2026-07-08', hash: '56d1a0d', type: 'fix', scope: null, title: "durably archive every generation, never store ephemeral provider URLs" },
	{ date: '2026-07-08', hash: '3c3c56d', type: 'feat', scope: null, title: "add social publishing infrastructure, billing pricing matrix, and docker-compose deployment support" },
	{ date: '2026-07-08', hash: '537532c', type: 'feat', scope: null, title: "implement backend API engine with SSRF protection and multi-path content orchestration" },
	{ date: '2026-07-08', hash: '2f636c5', type: 'feat', scope: null, title: "implement comprehensive content review workflow including dashboard, scheduler, and API integration" },
	{ date: '2026-07-09', hash: 'f867a18', type: 'fix', scope: null, title: "add undici dependency for SSRF-pinned safe-fetch" },
	{ date: '2026-07-11', hash: '2bf45b4', type: 'feat', scope: null, title: "audible b-roll, per-persona voices, async generation jobs, guided reference-kit flow" },
	{ date: '2026-07-11', hash: 'b7625ba', type: 'fix', scope: null, title: "stop shadowing the global fetch in generate.ts (took every generation route down)" },
	{ date: '2026-07-12', hash: 'fa8a136', type: 'feat', scope: null, title: "confirm-before-generate composer, asset preview, and live generation progress", milestone: "Confirm-before-generate composer \u2014 nothing spends money without an explicit approval." },
	{ date: '2026-07-12', hash: '6004cb6', type: 'feat', scope: null, title: "selectable generation models \u2014 user-controlled budget vs quality" },
	{ date: '2026-07-12', hash: '9d534c6', type: 'feat', scope: null, title: "implement multi-modal content generation pipeline with support for AI-driven still, video, and spokesperson production." },
	{ date: '2026-07-12', hash: '2cee607', type: 'feat', scope: null, title: "factual per-post observability, identity-preserving avatar regeneration, appearance system" },
	{ date: '2026-07-12', hash: '1c440d2', type: 'feat', scope: null, title: "cast per-persona voices from the name (nationality/accent \u2192 catalog match)" },
	{ date: '2026-07-12', hash: 'ad4ff3d', type: 'fix', scope: null, title: "stop Instagram connect timing out (\"Failed to fetch\") behind the prod proxy" },
	{ date: '2026-07-12', hash: 'b004fa4', type: 'feat', scope: null, title: "opt-in captions + AI-badge toggles, OmniHuman lip-sync, factual burn provenance" },
	{ date: '2026-07-12', hash: '9b8e64e', type: 'feat', scope: null, title: "Post Now (publish a draft/scheduled post immediately) + persona/drawer UI wiring" },
	{ date: '2026-07-12', hash: '55524f1', type: 'fix', scope: null, title: "install ffmpeg + DejaVu font in the prod image so caption/badge burn works" },
	{ date: '2026-07-12', hash: '0e5c709', type: 'feat', scope: null, title: "composer shows the true video pipeline (spokesperson\u2192OmniHuman) + per-run format control" },
	{ date: '2026-07-12', hash: '9e42811', type: 'feat', scope: null, title: "profile pictures respect persona ethnicity + look unique per persona" },
	{ date: '2026-07-12', hash: 'f265d89', type: 'fix', scope: null, title: "persist the generated persona profile automatically (no more re-generating every visit)" },
	{ date: '2026-07-13', hash: 'bad44dd', type: 'fix', scope: null, title: "persona generations never invent a stray name for the audience avatar" },
	{ date: '2026-07-13', hash: 'e31cbc4', type: 'feat', scope: null, title: "brand-brief-driven Agent Generator \u2014 unique personas from a brand + direction, ideas, fully configured" },
	{ date: '2026-07-13', hash: '622bebe', type: 'feat', scope: null, title: "review queue shows all pending content across personas + agent/platform/status filters" },
	{ date: '2026-07-13', hash: '7aab113', type: 'feat', scope: null, title: "generator step 2 surfaces the real persona profile; drop the avatar-gradient picker" },
	{ date: '2026-07-13', hash: '2b1e5e4', type: 'fix', scope: null, title: "truthful post counts, name-driven gender, resilient voice, confirm-before-spend on drafts" },
	{ date: '2026-07-13', hash: '8d56599', type: 'feat', scope: null, title: "add persona management and calendar routes to the portal module" },
	{ date: '2026-07-13', hash: 'cdec0f9', type: 'refactor', scope: null, title: "calendar layout\u2014narrower sidebar, day/week/month view filters, Postiz-style architecture" },
	{ date: '2026-07-14', hash: 'ef033d9', type: 'fix', scope: null, title: "calendar rework \u2014 real Day/Week/Month views, in-page personas rail, Postiz-style toolbar" },
	{ date: '2026-07-14', hash: 'ed0d603', type: 'feat', scope: null, title: "add zernio_keys table and agent association to support multiple per-persona API keys", milestone: "Zernio Key Manager \u2014 multiple publishing keys with per-persona assignment." },
	{ date: '2026-07-21', hash: '381825d', type: 'feat', scope: null, title: "implement server-side request resolution and generation orchestration with new composer component and backend services" },
	{ date: '2026-07-21', hash: 'eff9b54', type: 'feat', scope: null, title: "implement agent persona management dashboard and identity verification utilities" },
	{ date: '2026-07-21', hash: '9d22b8b', type: 'chore', scope: null, title: "remove unused file and associated references" },
	{ date: '2026-07-21', hash: '633c101', type: 'feat', scope: null, title: "implement persona identity resolution, agent generation services, and associated API endpoints" },
	{ date: '2026-07-21', hash: '3173bed', type: 'feat', scope: null, title: "implement comprehensive settings page for user profile, notification preferences, and multi-account Zernio key management" },
	{ date: '2026-07-21', hash: 'd516d7e', type: 'fix', scope: null, title: "robust brand-brief population \u2014 product photos, real logos, wizard re-seeding" },
	{ date: '2026-07-22', hash: '5fce188', type: 'feat', scope: null, title: "implement comprehensive persona management dashboard with integrated feed, profile configuration, and generation workflows" },
	{ date: '2026-07-22', hash: '50a5fdb', type: 'feat', scope: null, title: "implement asynchronous AI character portrait generation and reference sheet workflow" },
	{ date: '2026-07-22', hash: 'dd9cb3a', type: 'feat', scope: null, title: "initialize Svelte project and add backfill-faststart script", milestone: "personagen-svelte initialized \u2014 the codebase the app runs on today." },
	{ date: '2026-07-22', hash: '2d9ccc7', type: 'feat', scope: null, title: "implement interactive PostCard component with generation progress, error handling, and inline video playback support" },
	{ date: '2026-07-22', hash: '2b2a6eb', type: 'feat', scope: null, title: "implement PostCard and PostDrawer components for interactive post management and visualization" },
	{ date: '2026-07-22', hash: '6b2caa9', type: 'fix', scope: null, title: "verified publishing \u2014 never claim published without platform confirmation" },
	{ date: '2026-07-22', hash: '34b4513', type: 'fix', scope: null, title: "verification/analytics must use the key that created the Zernio post" },
	{ date: '2026-07-25', hash: '7d4e90a', type: 'feat', scope: null, title: "delete option for brand briefs" },
	{ date: '2026-07-25', hash: '1fbd7e1', type: 'feat', scope: null, title: "brand theme moves to Settings; enlargeable logo; editable/selectable products" },
	{ date: '2026-07-25', hash: '31e3483', type: 'feat', scope: null, title: "calendar as a first-class surface \u2014 shared CalendarView, persona Calendar tab, analytics strip, one-click flows", milestone: "Calendar becomes a first-class surface with the shared CalendarView." },
	{ date: '2026-07-25', hash: '5dd5ba0', type: 'feat', scope: null, title: "implement ui-ux-pro-max skill framework with data validation tools and expanded svelte UI components" },
	{ date: '2026-07-25', hash: '122bd7c', type: 'chore', scope: null, title: "checkpoint before UX makeover refactor" },
	{ date: '2026-07-25', hash: '4cba6bc', type: 'chore', scope: null, title: "normalize line endings" },
	{ date: '2026-07-25', hash: '0d9975c', type: 'feat', scope: null, title: "implement design system components, accessibility hardening, and server-side autopilot and budget-tracking improvements", milestone: "Design-system components, accessibility hardening, and budget tracking in one sweep." },
	{ date: '2026-07-25', hash: '50004df', type: 'feat', scope: null, title: "manageability contract \u2014 edit, multi-select, delete, enlarge across the app" },
	{ date: '2026-07-26', hash: '3fe6a53', type: 'docs', scope: null, title: "add user walkthroughs to README" },
	{ date: '2026-07-29', hash: 'd132bdd', type: 'docs', scope: null, title: "rewrite README walkthroughs around the three ready-to-use personas" },
	{ date: '2026-07-29', hash: '22864e7', type: 'chore', scope: null, title: "provision one-command verification for personagen-svelte" },
	{ date: '2026-08-02', hash: '317d321', type: 'feat', scope: null, title: "UX makeover pass \u2014 dialog action, url-state, design-system polish" },
	{ date: '2026-08-02', hash: '6d1035f', type: 'feat', scope: null, title: "add EasyPanel project configuration exporter and post review management dashboard" },
	{ date: '2026-08-02', hash: '68848a4', type: 'feat', scope: "settings", title: "sub-nav rail with ?section= deep links (UX-ASSESSMENT 4.3)" },
	{ date: '2026-08-02', hash: '7bd5f5e', type: 'feat', scope: null, title: "move the Content Intelligence wizard to its own route" },
	{ date: '2026-08-02', hash: 'd4257ee', type: 'other', scope: null, title: "Merge branch 'worktree-agent-aa58dd1be770c8429'" },
	{ date: '2026-08-02', hash: '941885a', type: 'other', scope: null, title: "Merge branch 'worktree-agent-a7d2aa53867e4d0f5'" },
	{ date: '2026-08-02', hash: '8f9472c', type: 'chore', scope: null, title: "move ui-ux-pro-max skill to global ~/.claude/skills" },
	{ date: '2026-08-02', hash: 'f58e73f', type: 'feat', scope: null, title: "Studio tab template catalog \u2014 archetype scaffolds for one-click composer prefills" },
	{ date: '2026-08-02', hash: '12953ce', type: 'docs', scope: null, title: "align user walkthroughs with the merged UX makeover" },
	{ date: '2026-08-02', hash: 'cae49df', type: 'feat', scope: null, title: "implement favorites system, database migrations, and supporting API services for persona project management" },
	{ date: '2026-08-02', hash: 'a8db5f3', type: 'feat', scope: null, title: "implement core services, API routes, and UI components for content generation, post management, and persona blueprints" },
	{ date: '2026-08-04', hash: '238861d', type: 'feat', scope: null, title: "in-app Guides page \u2014 plain-language how-tos for every feature" },
	{ date: '2026-08-07', hash: 'd9999eb', type: 'feat', scope: null, title: "visual Guides \u2014 real screenshots per step, full feature coverage" },
	{ date: '2026-08-08', hash: 'faccb24', type: 'feat', scope: null, title: "implement persona generation workflow and backend services for agent management and profile configuration" },
	{ date: '2026-08-08', hash: '72dda44', type: 'feat', scope: "models", title: "read-only reference values + real age on discovered models" },
	{ date: '2026-08-08', hash: '03fe3b4', type: 'feat', scope: null, title: "immersive Guides + real-account screenshots, quick fixes, nested nav", milestone: "Guides go immersive \u2014 the in-app documentation hub this page lives in." },
	{ date: '2026-08-08', hash: '81a6dcb', type: 'feat', scope: "models", title: "provider/age/quality filters, replacement candidates, slot swap" },
	{ date: '2026-08-08', hash: '942e5b3', type: 'feat', scope: "models", title: "any discovered model can take any slot \u2014 closes the reverse swap" },
	{ date: '2026-08-08', hash: 'f36a352', type: 'fix', scope: null, title: "close the identity-kit data-loss path, login email validation, deep links" },
	{ date: '2026-08-08', hash: '0961c0b', type: 'feat', scope: null, title: "add model management view with filtering, sorting, and recommendation logic", milestone: "Model Manager \u2014 the roster, discovery, and value rankings for generation models." },
	{ date: '2026-08-08', hash: '224ca57', type: 'feat', scope: null, title: "introduce studio template system and catalog for automated content generation workflows", milestone: "Studio template system \u2014 one-click archetype scaffolds for every persona." },
	{ date: '2026-08-08', hash: '35e94de', type: 'perf', scope: "images", title: "serve resized WebP thumbnails instead of full-size originals" },
	{ date: '2026-08-08', hash: '27109bb', type: 'fix', scope: null, title: "content-hashed guide screenshots \u2014 stale caches structurally impossible" },
];
